version: '2'
services:
  ida_project-web:
    build: ./docker/python
    command: >
      bash -c "yes | pip3 install -r /ida_project/requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./project:/ida_project
    ports:
      - "8001:8000"
    env_file:
      - ./project/.dev.env
