# Generated by Django 3.1 on 2020-08-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_loader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
