# Generated by Django 3.1 on 2020-08-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_loader', '0003_auto_20200815_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_resized',
            field=models.TextField(default=''),
        ),
    ]
