# Generated by Django 3.1 on 2020-08-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_loader', '0002_auto_20200808_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='path',
            new_name='image',
        ),
    ]
